name: Cron Test Workflow 2

on:
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos para teste
  workflow_dispatch: # Permite execução manual

jobs:
  cron-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Exibir mensagem
        run: echo "O workflow foi executado com sucesso!"
